title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://tutran21195.github.io/steg-labs/

aux_links:
  Labs Repository: https://github.com/TuTran21195/steg-labs
